---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: tautulli-config
spec:
    storageClassName: tautulli-config
    capacity:
        storage: 128G
    accessModes:
        - ReadWriteOnce
    nfs:
        server: 192.168.1.200
        path: /mnt/primary/low-priority/plex/tautulli

