kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: true-command
spec:
  selector:
    matchLabels:
      app: true-command
  serviceName: true-command
  replicas: 1
  template:
    metadata:
      labels:
        app: true-command
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: 'ixsystems/truecommand:2.0.2'
          imagePullPolicy: IfNotPresent
          name: true-command
          ports:
              - containerPort: 80
                name: http
              - containerPort: 443
                name: https
          volumeMounts:
            - mountPath: /data
              name: true-command
              readOnly: false
          livenessProbe:
            tcpSocket:
              port: http
            timeoutSeconds: 15
            initialDelaySeconds: 15
            periodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: true-command 
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: true-command 
        resources:
          requests:
            storage: 16G
---
apiVersion: v1
kind: Service
metadata:
    name: true-command
spec:
    type: NodePort
    selector:
        statefulset.kubernetes.io/pod-name: true-command-0
    ports:
        - name: http
          protocol: TCP
          port: 80
          nodePort: 30000

