---
kind: StatefulSet
apiVersion: apps/v1
metadata:
    name: plex
spec:
    selector:
        matchLabels:
            app: plex
    serviceName: plex
    # start with 1 and then use the scale command to add more later
    replicas: 1
    template:
        metadata:
            labels:
                app: plex
        spec:
            hostNetwork: true
            terminationGracePeriodSeconds: 10
            affinity:
                podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        -
                            labelSelector:
                                matchExpressions:
                                -
                                    key: "app"
                                    operator: In
                                    values:
                                    -
                                        plex
                            topologyKey: "kubernetes.io/hostname"
            containers:
                -
                    env:
                        -
                            name: PLEX_CLAIM
                            valueFrom:
                                secretKeyRef:
                                    name: plex
                                    key: claim-token
                        -
                            name: TZ
                            value: "America/New_York"
                    image: 'plexinc/pms-docker:1.19.4.2935-79e214ead'
                    imagePullPolicy: IfNotPresent
                    name: plex
                    volumeMounts:
                        -
                            mountPath: /video/H.265/movies/blu-ray
                            name: avc-blu-ray-movies
                        -
                            mountPath: /video/H.265/movies/dvd
                            name: avc-dvd-movies
                        -
                            mountPath: /video/H.265/tv/blu-ray
                            name: avc-blu-ray-tv
                        -
                            mountPath: /video/H.265/tv/dvd
                            name: avc-dvd-tv
                        -
                            mountPath: /config
                            name: plex-config
    volumeClaimTemplates:
        -
            metadata:
                name: plex-config
            spec:
                accessModes:
                    - ReadWriteOnce
                storageClassName: plex-config
                resources:
                    requests:
                        storage: 128G
        -
            metadata:
                name: avc-blu-ray-movies
            spec:
                accessModes:
                    - ReadOnlyMany
                storageClassName: avc-blu-ray-movies
                resources:
                    requests:
                        storage: 128G
        -
            metadata:
                name: avc-dvd-movies
            spec:
                accessModes:
                    - ReadOnlyMany
                storageClassName: avc-dvd-movies
                resources:
                    requests:
                        storage: 128G
        -
            metadata:
                name: avc-blu-ray-tv
            spec:
                accessModes:
                    - ReadOnlyMany
                storageClassName: avc-blu-ray-tv
                resources:
                    requests:
                        storage: 128G
        -
            metadata:
                name: avc-dvd-tv
            spec:
                accessModes:
                    - ReadOnlyMany
                storageClassName: avc-dvd-tv
                resources:
                    requests:
                        storage: 128G
