---
kind: StatefulSet
apiVersion: apps/v1
metadata:
    name: plex
spec:
    selector:
        matchLabels:
            app: plex
    serviceName: plex
    # start with 1 and then use the scale command to add more later
    replicas: 2
    template:
        metadata:
            labels:
                app: plex
        spec:
            hostNetwork: true
            terminationGracePeriodSeconds: 10
            affinity:
                podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        -
                            labelSelector:
                                matchExpressions:
                                -
                                    key: "app"
                                    operator: In
                                    values:
                                    -
                                        plex
                            topologyKey: "kubernetes.io/hostname"
            containers:
                -
                    env:
                        -
                            name: PLEX_CLAIM
                            valueFrom:
                                secretKeyRef:
                                    name: plex
                                    key: claim-token
                        -
                            name: TZ
                            value: "America/New_York"
                    image: 'plexinc/pms-docker:1.19.5.3112-b23ab3896'
                    imagePullPolicy: IfNotPresent
                    name: plex
                    volumeMounts:
                        -
                            mountPath: /video
                            name: video
                            readOnly: true
                        -
                            mountPath: /music
                            name: music
                            readOnly: true
                        -
                            mountPath: /config
                            name: plex-config
                            readOnly: false
    volumeClaimTemplates:
        -
            metadata:
                name: plex-config
            spec:
                accessModes:
                    - ReadWriteOnce
                storageClassName: plex-config
                resources:
                    requests:
                        storage: 1G
        -
            metadata:
                name: video
            spec:
                accessModes:
                    - ReadOnlyMany
                storageClassName: video
                resources:
                    requests:
                        storage: 128G
        -
            metadata:
                name: music
            spec:
                accessModes:
                    - ReadOnlyMany
                storageClassName: music
                resources:
                    requests:
                        storage: 128G
