kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: plex
spec:
  selector:
    matchLabels:
      app: plex
  serviceName: plex
  replicas: 3
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - plex
              topologyKey: kubernetes.io/hostname
      volumes:
        - name: video
          nfs:
            path: /mnt/primary/low-priority/videos
            readOnly: true
            server: 192.168.1.200
        - name: music
          nfs:
            path: /mnt/primary/medium-priority/music
            readOnly: true
            server: 192.168.1.200
        - name: photos
          nfs:
            path: /mnt/primary/high-priority/photos
            readOnly: true
            server: 192.168.1.200
      containers:
        - env:
            - name: PLEX_CLAIM
              valueFrom:
                secretKeyRef:
                  name: plex
                  key: claim-token
            - name: TZ
              value: America/New_York
          image: 'linuxserver/plex:1.24.3.5033-757abe6b4-ls75'
          imagePullPolicy: IfNotPresent
          name: plex
          volumeMounts:
            - mountPath: /video
              name: video
              readOnly: true
            - mountPath: /music
              name: music
              readOnly: true
            - mountPath: /photos
              name: photos
              readOnly: true
            - mountPath: /config
              name: plex-config
              readOnly: false
            - mountPath: /transcode
              name: plex-transcode
              readOnly: false
          livenessProbe:
            tcpSocket:
              port: 32400
            timeoutSeconds: 15
            initialDelaySeconds: 15
            periodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: plex-config
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: plex-config
        resources:
          requests:
            storage: 64G
    - metadata:
        name: plex-transcode
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: plex-transcode
        resources:
          requests:
            storage: 1G
