---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-config-delta
spec:
    storageClassName: plex-config
    capacity:
        storage: 32G
    accessModes:
        - ReadWriteOnce
    iscsi:
          targetPortal: 192.168.1.200:3260
          iqn: iqn.2005-10.org.freenas.ctl:plex-configuration-delta
          lun: 0
          fsType: ext4
          readOnly: false
