---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-media-alpha
spec:
    storageClassName: plex-media
    capacity:
        storage: 5T
    accessModes:
        - ReadOnlyMany
    nfs:
        server: 192.168.1.211
        path: /mnt/secondary/low-priority/media
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-media-bravo
spec:
    storageClassName: plex-media
    capacity:
        storage: 5T
    accessModes:
        - ReadOnlyMany
    nfs:
        server: 192.168.1.211
        path: /mnt/secondary/low-priority/media
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-media-charlie
spec:
    storageClassName: plex-media
    capacity:
        storage: 5T
    accessModes:
        - ReadOnlyMany
    nfs:
        server: 192.168.1.211
        path: /mnt/secondary/low-priority/media
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-media-delta
spec:
    storageClassName: plex-media
    capacity:
        storage: 5T
    accessModes:
        - ReadOnlyMany
    nfs:
        server: 192.168.1.211
        path: /mnt/secondary/low-priority/media
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-config-alpha
spec:
    storageClassName: plex-config
    capacity:
        storage: 105G
    accessModes:
        - ReadWriteOnce
    nfs:
        server: 192.168.1.211
        path: /mnt/secondary/low-priority/plex/alpha
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-config-bravo
spec:
    storageClassName: plex-config
    capacity:
        storage: 105G
    accessModes:
        - ReadWriteOnce
    nfs:
        server: 192.168.1.211
        path: /mnt/secondary/low-priority/plex/bravo
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-config-charlie
spec:
    storageClassName: plex-config
    capacity:
        storage: 105G
    accessModes:
        - ReadWriteOnce
    nfs:
        server: 192.168.1.211
        path: /mnt/secondary/low-priority/plex/charlie
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-config-delta
spec:
    storageClassName: plex-config
    capacity:
        storage: 105G
    accessModes:
        - ReadWriteOnce
    nfs:
        server: 192.168.1.211
        path: /mnt/secondary/low-priority/plex/delta
