---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: avc-blu-ray-movies
spec:
    storageClassName: avc-blu-ray-movies
    capacity:
        storage: 1T
    accessModes:
        - ReadOnlyMany
    nfs:
        server: 192.168.1.200
        path: /mnt/primary/low-priority/video/H.265/movies/blu-ray
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: avc-dvd-movies
spec:
    storageClassName: avc-dvd-movies
    capacity:
        storage: 1T
    accessModes:
        - ReadOnlyMany
    nfs:
        server: 192.168.1.200
        path: /mnt/primary/low-priority/video/H.265/movies/dvd
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: avc-blu-ray-tv
spec:
    storageClassName: avc-blu-ray-tv
    capacity:
        storage: 1T
    accessModes:
        - ReadOnlyMany
    nfs:
        server: 192.168.1.200
        path: /mnt/primary/low-priority/video/H.265/tv/blu-ray
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: avc-dvd-tv
spec:
    storageClassName: avc-dvd-tv
    capacity:
        storage: 1T
    accessModes:
        - ReadOnlyMany
    nfs:
        server: 192.168.1.200
        path: /mnt/primary/low-priority/video/H.265/tv/dvd
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-config-alpha
spec:
    storageClassName: plex-config
    capacity:
        storage: 128G
    accessModes:
        - ReadWriteOnce
    nfs:
        server: 192.168.1.200
        path: /mnt/primary/low-priority/plex/alpha
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-config-bravo
spec:
    storageClassName: plex-config
    capacity:
        storage: 128G
    accessModes:
        - ReadWriteOnce
    nfs:
        server: 192.168.1.200
        path: /mnt/primary/low-priority/plex/bravo
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-config-charlie
spec:
    storageClassName: plex-config
    capacity:
        storage: 128G
    accessModes:
        - ReadWriteOnce
    nfs:
        server: 192.168.1.200
        path: /mnt/primary/low-priority/plex/charlie
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-config-delta
spec:
    storageClassName: plex-config
    capacity:
        storage: 128G
    accessModes:
        - ReadWriteOnce
    nfs:
        server: 192.168.1.200
        path: /mnt/primary/low-priority/plex/delta
