---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: netboot-xyz-alpha
spec:
  storageClassName: netboot-xyz
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: '192.168.1.200:3260'
    iqn: 'iqn.2005-10.org.freenas.ctl:netboot-xyz-alpha'
    lun: 0
    fsType: ext4
    readOnly: false
