---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: unifi-controller
spec:
    storageClassName: unifi-controller
    capacity:
        storage: 128M
    accessModes:
        - ReadWriteOnce
    nfs:
        server: 192.168.1.200
        path: /mnt/primary/medium-priority/ums

